### ISSUE TITLE
Refactor of reference section to explicit python classes

### ISSUE THREAD

**Issue by danimtb** [conan-io/docs#1011]
As Conan usage is growing there are more and more functionalities available and the features inside recipes are getting more complex.

The motivation of this is issue comes from the need to add explanation about new clases that have been recently introduced like `ConanInvalidConfiguration` and `Version`.

But the way the reference section is structured does not provide a good place for them: They are not tools and they are not a mandatory part of a *conanfile.py*. Adding a new "misc" section as suggested in #840 could work but will not be easy to find by users and will quickly grow with a bunch of different things (and probably not only python classes/functions).

Hearing also some of the comments in #569 I also find it difficult to explain things such as ``cpp_info`` or ``copy()`` in the right way just inside *conanfile.py*. Moreover, as we are adding ourselves functionalities to be placed inside *conanfile.py* but outside the `ConanFIle` class like Python requires this becomes more confusing.

There are other points for this refactor: 
- Many sections in the reference are only related to *conanfile.py* (not only ConanFile) class
- There would be entry users not interested on python things: e.g. If I use a *conanfile.txt* why do I have at the same level "Build helpers"?
- Tools and Build helpers sections follow a pattern quite understandable: Definition of the attribute/method, brief explanation of the functionality with an example and description of the useful parameters.

My proposal for a new structure:
```
reference
├──commands
├──conanfile.txt
├──conanfile.py
│     ├───ConanFile class: (Attributes & Methods with definition and usage description with example)
│     ├───Build Helpers
│     ├───Python requires
│     ├───Output and running
│     ├───Other Classes
│     │   ├───ConanInvalidConfiguration
│     │   └───Version
│     └───Tools
├──generators
├──profiles
├──config_files
├──environment variables
└───Hooks
```

This places many of the stuff in the *conanfile.py* section (you may argue this is another level/click the user has to do down) but makes a comprehensive and intuitive organization e.g. "All of this stuff is only important if I am working with a *conanfile.py*".

My two main points for this:
- Entry users would only care about commands, conanfile.txt and generators. Don't bother them with a lot of python things.
- "Hardcore" conanfile.py users will find a detailed and dedicated section with good reference of the classes and its usage avoiding dumb assumptions like *conanfile.py == class ConanFile*

Any suggestion will be more than welcome.

**Comment by uilianries** [comment]
I think people is more interested in 3 points:

- How to fix some error
- How to do a recipe
- Reference

Since I have read the documentation often, I can find anything that I need.
But in my last job my co-workers often told me that the documentation was really bad to find a solution to any problem or to do something specific in a recipe. Now we have a good FAQ I think.

I really like the "Mastering Conan" section, not because it's well written, but because it's focused, I can find everything I need without the search bar. I think your idea of putting together all the important stuff related to conanfile is a great idea. Anyone can read a section and maybe find what they need in the next section before using the search engine.

Maybe you could point possible problems when refactoring, just linking to the FAQ -- the classical case where you follow the documented steps but dont work in your machine.

**Comment by danimtb** [comment]
This has been replaced by #1156
