### ISSUE TITLE
document behavior of tools.collect_libs in editable mode

### ISSUE THREAD

**Issue by SSE4** [conan-io/docs#1254]
`tools.collect_libs` does exactly the same irregardless of mode, but some users found it non-obvious, would be nice to add some note in docs to describe that it's just stupid wrapper which scans `self.cpp_info.libdirs`

**Comment by danimtb** [comment]
The documentation already says that: https://docs.conan.io/en/latest/reference/tools.html#tools-collect-libs 🙄  -> 👀 📄

**Comment by SSE4** [comment]
for users it's currently not obvious if behavior changes in editable mode, I think adding an additional note would make it more explicit

**Comment by danimtb** [comment]
The behavior does not change in editable/workspace mode vs. normal mode... I think the description is clear and users only have to read how it works.

Stating something like a warning saying "Warning: This tool works the same regardless of the _mode_ of the package" sounds weird and obvious to me and it could be applied to ALL the tools (Otherwise one could think that some of the tools work differently in regard to the package mode...)

**Comment by danimtb** [comment]
How can we improve this then? I don't really see a way to state this more clearly. Can we close this otherwise?

**Comment by SSE4** [comment]
yeah, I think it's visible enough, let's close
