### ISSUE TITLE
add FAQ entry for unwanted files in packages

### ISSUE THREAD

**Issue by SSE4** [conan-io/docs#1314]
we have constantly receiving issues, requests and questions around various files. for instance, to package .pdb files with debug information, or .pc files, or .cmake config files. it would be nice to document why don't we include such files into the packages, and what's recommended to be used instead (hooks, generators, in-source builds, etc.):
- PDB files (and debug information in general, like .dwarf, .debug, etc.)
- Libtool (.la) files
- pkg-config (.pc) files
- cmake FindXXX.cmake and xxx-config.cmake files
- anything else we're currently restricting from our packages (am I missing something?)

may be also describe disadvantages of these files, like that they may contain hard-coded paths, may not support transitive dependencies, etc.
/cc @jgsogo

**Comment by memsharded** [comment]
These are not unwanted files in packages in all cases, it has to be clear that they are not good for public open source packages in conan-center and other public repositories. Especially the Debug files.

The history about .pc and .cmake files has to be very clear, users might try that directly in their own packages, but they must be aware of the intrinsic limitations of the approach and the risks they can have if using those files as they come from many libraries (like linking the system old library instead of the up to date Conan one)

**Comment by danimtb** [comment]
Those kind of files are not "unwanted", just depends on the usage and the context of the recipe (open source, internal, customized recipe...)

I think this is something we should add to the contribution guidelines for Conan Center but not for Conan in general.

There is an open issue about this, so probably you should comment there.

**Comment by SSE4** [comment]
this has been documented in the conan center FAQ, and hooks already handle that
