### ISSUE TITLE
conandata.yml documentation uses non prefered method to demonstrate patching

### ISSUE THREAD

**Issue by ItsBasi** [conan-io/docs#1779]
The section https://docs.conan.io/en/latest/reference/tools.html#tools-patch recommends to patch sources in the build step, but the example in https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html#conandata-yml patches the files during the source step.

**Comment by memsharded** [comment]
Hi @ItsBasi 


The recommendation would be:

- Use the ``source()`` method for things that apply to the source for all possible configurations. If the patches apply to all platforms and compilers, it is good to apply them on the ``source()`` method
- Use the ``build()`` method if the patches are specific for a certain platform or configuration.

I agree this can be clarified in the docs, lets fix it, thanks for reporting!

**Comment by uilianries** [comment]
@memsharded I disagree for the first point.

patch should be applied in build method, because when elaborating a new recipe, any change in patch (and it happens when developing), will require a new Download, as the source not the same. Also, if you want to read the original source code, the source folder will contain the untouched version. That's very useful when developing a new recipe or doing a fix.

That's why we apply patch only under build() in CCI recipes. The exception is for header-only, when build folder is not required.

**Comment by ItsBasi** [comment]
I found that under https://docs.conan.io/en/latest/reference/conanfile/methods.html#source, the note block elaborates on patching durring source or build a bit.
I think it would be better if this note block is moved to a section about patching.

**Comment by ItsBasi** [comment]
Thanks for improving this
