### ISSUE TITLE
Add feature's version for new methods

### ISSUE THREAD

**Issue by uilianries** [conan-io/docs#2046]
Hi!

As `required_conan_version` requires a specific version related to which features we want to use in recipe, we need to know Conan releases too.

Usually I need to check the changelog to discover when a feature was released, but not all are clear. For instance, `validate()` can not be found when searching for "validate" on changelog.

My proposal is adding which version corresponds for that feature. For example:

![Screenshot_2021-03-19 Methods — conan 1 34 0 documentation(1)](https://user-images.githubusercontent.com/4870173/111840895-dbb1a580-88db-11eb-99f4-fdd97185ed17.png)

Where 1.33.0 link points to [1.33.0 changelog](https://docs.conan.io/en/latest/changelog.html#jan-2021).

**Comment by memsharded** [comment]
Yes, lets do this.

From now on, relevant changes to the docs, specially when introducing new features, the version should be added to the docs.
The only challenging thing is the link: at the moment of writing the PR to the docs, the tag is not ready, not possible to link to it, the PR will fail because of broken link (even if we avoid this check, but if the release slips to next month, then links will be broken anyway). It is not easy either to link the docs PR, because that would be the PR currently being created. The best would be to link the PR that added the feature, or not add anything (as Python docs, for example). I think not linking anything is not a problem, and will be the simplest.

**Comment by uilianries** [comment]
I would say it would be great adding some features from Conan >= 1.32.0, because they are frequently used on Conan Center Index, where we have to review and point the changelog as reference to say: "validate() requires 1.33, please take a look on changelog...".

**Comment by memsharded** [comment]
Ok, please do a PR with those most frequent use cases, if that can help with support for ConanCenter, then perfect!

**Comment by uilianries** [comment]
fixed by #2048
