### ISSUE TITLE
[question] How do you use conan.tools.cmake.CMake with conanbuildinfo.cmake?

### ISSUE THREAD

**Issue by jkleve** [conan-io/docs#2359]
I set up my cmake project to include conanbuildinfo.cmake and do the basic setup. There's a lot of useful stuff in there so I'd like to keep using it. I switched from conans.CMake to conan.tools.cmake.CMake and now when I try to create the package I get:

```sh
ERROR: my-example/0.1: Error in build() method, line 90
        cmake = CMake(self)
        ConanException: Usage of toolchain is only supported with 'cmake_find_package' or 'cmake_find_package_multi' generators
```

So my question is why is the `cmake` generator forbidden with `conan.tools.cmake.CMake`?

See [cmake.py:13](https://github.com/conan-io/conan/blob/c5989d7e3d47af99117604b00012717fbbf205ac/conan/tools/cmake/cmake.py#L13)
```py
def _validate_recipe(conanfile):
    forbidden_generators = ["cmake", "cmake_multi"]
    if any(it in conanfile.generators for it in forbidden_generators):
        raise ConanException("Usage of toolchain is only supported with 'cmake_find_package'"
                             " or 'cmake_find_package_multi' generators")
```

**Comment by memsharded** [comment]
Moving this to the "docs" repo.

> We should mark the old CMake build helper as going away in 2.0 and/or mention this is not to be used with the newer CMake method

This is not easy to do in production code, because that is the declared "stable" integration, so we cannot pollute it with warnings or anything, because users will complain. So it needs to be a docs thing (which is also in a bad place at the moment, we know, because it is not easy to swap the old by new without breaking somethings, because for example all recipes in ConanCenter still uses the old integrations)

**Comment by jkleve** [comment]
We can go ahead and close this if you'd like. It's documented in code.
