### ISSUE TITLE
Clion plugin hasn't been updated for 3years and has become incompatible

### ISSUE THREAD

**Issue by alexisfrjp** [conan-io/docs#2818]
* https://plugins.jetbrains.com/plugin/11956-conan

![image](https://user-images.githubusercontent.com/6713988/203521596-980b1fd9-0d3a-4b79-88c8-8e2b90769793.png)
`Not compatible with the version of your running IDE (CLion 2022.2.4)`

https://github.com/conan-io/docs/blob/master/integrations/ide/clion.rst

**Comment by memsharded** [comment]
Hi @alexisfrjp 

Yes, sorry, we are aware of this. We have changed our build system integrations and we have been very busy preparing the 2.0, which will be a super major new version, so we didn't have time to maintain this plugin. We will investigate what to do with it after 2.0.

**Comment by hwhsu1231** [comment]
In terms of CMake, I think this plugin might not be required so much if the following repos can be kept maintained and improved:

* [cmake-conan](https://github.com/conan-io/cmake-conan)
* [cmake-conan-setup](https://github.com/hwhsu1231/cmake-conan-setup)

since CLion uses CMake as the major build system.
