### ISSUE TITLE
[1.6] "Host platform" is not correct

### ISSUE THREAD

**Issue by AndreiCherniaev** [conan-io/docs#3102]
On this [page](https://docs.conan.io/en/1.6/systems_cross_building/cross_building.html) you can see "Host platform: The platform on which the code will run". And "Target platform: Only when building a compiler" Is it right? I think no.

From cmake [docs](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html)
The system used to build the software will be called the “build **host**,” and the system for which the software is built will be called the “target system” or “target platform.” The target system usually runs a different operating system (or none at all) and/or runs on different hardware. A typical use case is in software development for embedded devices like network switches, mobile phones, or engine control units. In these cases, the target platform doesn’t have or is not able to run the required software development environment.

**Comment by memsharded** [comment]
Hi @AndreiCherniaev 

Thanks for your report.
I am afraid that this 1.6 docs is extremely outdated. Not only because Conan 2.0 is already out, but 1.6 is many years old.
We don't plan to maintain those docs anymore, so closing this. I'd recommend reporting over 2.0 docs, which are the ones under current development, thanks.
