### ISSUE TITLE
[bug] WARN: Name containing special chars is discouraged 'hello-world'

### ISSUE THREAD

**Issue by andrey-zherikov** [conan-io/docs#3329]
### Environment details

* Operating System+version: Windows 10
* Compiler+version: N/A
* Conan version: 2.0.9
* Python version: 3.11.2

### Steps to reproduce

```
conan new cmake_lib -d name=hello-world -d version=1.0
conan create .  
```

### Logs

```
> conan create . 

======== Exporting recipe to the cache ========
WARN: Name containing special chars is discouraged 'hello-world'
...
```

Note that `hello-world` is valid name according to [docs](https://docs.conan.io/2/reference/conanfile/attributes.html#name)

**Comment by SzBosch** [comment]
Can this warning be suppressed?

**Comment by memsharded** [comment]
At the moment it is not possible because this warning is not tagged, but there is a ``core:skip_warnings`` conf that can be used to silence warnings, maybe we could add a new tag.

In any case, this warning I'd  suggest not silencing it, it would just postpone the problems, it is much better recommended to rename it and get rid of the special char. I have seen a bunch of users being later affected by it later down the road, when other tool doesn't like the special chars in filenames

**Comment by memsharded** [comment]
We are finally removing this warning in https://github.com/conan-io/conan/pull/15920 for 2.3, there are too many packages in ConanCenter with "-", this would be too much to migrate.
