### ISSUE TITLE
Convert packages created by conan 1.61.0 to be useful with conan 2.0

### ISSUE THREAD

**Issue by Vasile-Creuco** [conan-io/docs#3444]
Hello!

Is it possible to convert an existing package created by Conan 1.61.0 to Conan 2.0?
I have some packages which are uploaded on remote and I downloaded them. Then I would like to use them like requirements and create some packages with Conan 2.0, but it doesn't work, because packages were created by Conan 1.61.0

Thank you!

**Comment by memsharded** [comment]
Hi @Vasile-Creuco 

Thanks for your question!

The package binaries in Conan 1.X and 2.0 have completely different ``package_id`` for both, and this is fundamental behavior to allow some important things for the migration:
- The package binaries in 1.X and 2.0 can be created from exactly the same recipe with the same version and same recipe revision. Actually, they should be using the same recipe with the modern 1.X syntax that is fully compatible with Conan 2.0
- The binaries from 1.X and 2.0 are actually different, even when built with the same configuration, because the ``package_id`` will contain different information, different rules, like different ``package_id_mode``.
- One of the design requirements is that the same server repositories could be used simultaneously for binaries created for Conan 1.X and 2.0. This is a way of not requiring extra repositories, not having to change the client repos, and not disrupting operations in general. Also it helps a lot in guaranteeing packages are created from the same recipe revisions.
- So the only way to achieve this was if the ``package_ids`` were actually different for 1.X and 2.0. They are "invisible" to each other. Conan 1.X will only list binaries created with Conan 1.X in ``conan search ...`` and Conan 2.0 will only list binaries created with Conan 2.0 in ``conan list ...``. They cannot even ``conan install`` the binaries created with the other version.

Also, the migration from 1.X and 2.0 can only be successful it the packages can be built with 2.0, it is the only real way to prove the recipes are fully compatible and everything is working correctly. The recommended way to do the migration is have a parallel CI pipeline that starts to build the packages for 2.0 too, from the same recipes revisions.


I hope this clarifies the behavior, please let me know. Thanks!
