### ISSUE TITLE
Review cross building && build_requires docs

### ISSUE THREAD

**Issue by lasote** [conan-io/docs#441]
To adapt to the new os_build, arch_build

**Comment by DavidZemon** [comment]
Not sure if this is the right place to make this comment, but looks looking at the top of the new `settings.yml` file in v1.0.0, one gets the impression that Conan can't run on anything other than 32- and 64-bit x86 platforms. Since it's a Python app, I'm guessing that isn't true... but I wouldn't blame anyone for thinking so. I have to imagine there are people out there using Conan on Raspberry Pis, and there are already talks of using Conan at my company for native development on our Arm systems rather than cross compiling from an Intel CPU.

**Comment by memsharded** [comment]
I think this could be a real issue, lets open a dedicated one in the main conan repo. Thanks!

**Comment by DavidZemon** [comment]
This would also be the right ticket to fix `conans.client.tools.oss.detected_architecture`:

```py
def detected_architecture():
    # FIXME: Very weak check but not very common to run conan in other architectures
    if "64" in platform.machine():
        return "x86_64"
    elif "86" in platform.machine():
        return "x86"
    return None
```

**Comment by memsharded** [comment]
Hi David,

The ``arch_build`` setting has been released in 1.0.2, but your proposed ``detected_architecture()`` wasn't added. Can you please clarify the fix, what is your code fixing? Thanks!

**Comment by DavidZemon** [comment]
Oh, sorry. I didn't mean to imply that I had any good suggestion for fixing it. Simply that the above function exists in Conan and, as the `FIXME` clearly states, isn't ideal.

**Comment by danimtb** [comment]
I think the documentation for this issue was already done here: https://docs.conan.io/en/latest/systems_cross_building/cross_building.html
and here:
http://docs.conan.io/en/latest/devtools/create_installer_packages.html

WDYT @lasote?

**Comment by danimtb** [comment]
I think documentation is good enough to mark this issue as solved. Please reopen/comment if necessary. Thanks!
