### ISSUE TITLE
CONAN_CMAKE_TOOLCHAIN_FILE is not documented

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/docs#581]
Hi,

I was really glad to find that there is a `CONAN_CMAKE_TOOLCHAIN_FILE` environment variable, unfortunately it is not present in the CMake helper page.

I ran `grep` on the source code :D.

**Comment by danimtb** [comment]
Hi @theodelrieu,

Have you checked this http://docs.conan.io/en/latest/reference/env_vars.html?highlight=CONAN_CMAKE_TOOLCHAIN_FILE#cmake-related-variables ?

**Comment by theodelrieu** [comment]
No I haven't seen it, I always go to the [helper](http://docs.conan.io/en/latest/reference/build_helpers/cmake.html?highlight=cmake#definitions) page.

Thanks for the link!

**Comment by danimtb** [comment]
I think that variable is not listed in the helper page because it is not set automatically for cross-building, it is a general env var for profiles.

In the helper you can always set the CMAKE_TOOLCHAIN_FILE definition but you would not want to hardcode de path there. That is the reason to list CONAN_CMAKE_TOOLCHAIN in the environment variable section.

I will add a link to the helper section. Thanks for reporting!
